### ISSUE TITLE
Cannot compile with cuda

### ISSUE THREAD

**Issue by evanthomas** [deeplearning4j/nd4s#114]
Hello,

I cannot compile nd4s with cuda support. This is what I did:

1. clone
2. edit build.sbt to
   1. change dl4j version to 0.9.1
   2. change the nd4l platform library dependence to `"org.nd4j" % "nd4j-cuda-8.0-platform" % nd4jVersion.value,`
3. `sbt compile`

This is my session:
```
$ git clone https://github.com/deeplearning4j/nd4s.git
Cloning into 'nd4s'...
remote: Counting objects: 1234, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 1234 (delta 3), reused 9 (delta 2), pack-reused 1221
Receiving objects: 100% (1234/1234), 161.16 KiB | 134.00 KiB/s, done.
Resolving deltas: 100% (472/472), done.

evan@dugsy MINGW64 ~/Documents/neurosim
$ cd nd4s/

evan@dugsy MINGW64 ~/Documents/neurosim/nd4s (master)
$ ls
build.sbt  LICENSE  nd4j_install.sh*  perform-release.sh*  project/  README.md  src/

[edit build.sbt]

evan@dugsy MINGW64 ~/Documents/neurosim/nd4s (master)
$ sbt compile
[info] Loading project definition from C:\Users\evan\Documents\neurosim\nd4s\project
[info] Updating {file:/C:/Users/evan/Documents/neurosim/nd4s/project/}nd4s-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to nd4s (in build file:/C:/Users/evan/Documents/neurosim/nd4s/)
[warn] Credentials file C:\Users\evan\.ivy2\.credentials does not exist
[info] Updating {file:/C:/Users/evan/Documents/neurosim/nd4s/}root...
[info] Resolving jline#jline;2.12.1 ...
[warn]  [FAILED     ] org.bytedeco.javacpp-presets#cuda;8.0-6.0-1.3!cuda.jar:  (0ms)
[warn] ==== local: tried
[warn]   C:\Users\evan\.ivy2\local\org.bytedeco.javacpp-presets\cuda\8.0-6.0-1.3\jars\cuda-${dependency.platform}.jar
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/cuda/8.0-6.0-1.3/cuda-8.0-6.0-1.3-${dependency.platform}.jar
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\evan\.sbt\preloaded\org.bytedeco.javacpp-presets\cuda\8.0-6.0-1.3\jars\cuda-${dependency.platform}.jar
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/evan/.sbt/preloaded/org/bytedeco/javacpp-presets/cuda/8.0-6.0-1.3/cuda-8.0-6.0-1.3-${dependency.platform}.jar
[warn] ==== sonatype-snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/cuda/8.0-6.0-1.3/cuda-8.0-6.0-1.3-${dependency.platform}.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::              FAILED DOWNLOADS            ::
[warn]  :: ^ see resolution messages for details  ^ ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.bytedeco.javacpp-presets#cuda;8.0-6.0-1.3!cuda.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: download failed: org.bytedeco.javacpp-presets#cuda;8.0-6.0-1.3!cuda.jar
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
        at sbt.IvySbt.withIvy(Ivy.scala:128)
        at sbt.IvySbt.withIvy(Ivy.scala:125)
        at sbt.IvySbt$Module.withModule(Ivy.scala:156)
        at sbt.IvyActions$.updateEither(IvyActions.scala:168)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1439)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1435)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1470)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1468)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1473)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1467)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1490)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1417)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1369)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[error] (*:update) sbt.ResolveException: download failed: org.bytedeco.javacpp-presets#cuda;8.0-6.0-1.3!cuda.jar
[error] Total time: 4 s, completed 21-Aug-2017 21:22:08
```

**Comment by saudet** [comment]
That seems to be a bug in sbt somewhere. It builds fine here after adding the following line and having the artifacts in the `~/.m2/repository` directory:
```scala
resolvers += Resolver.mavenLocal
```
Can you confirm?

**Comment by evan-wehi** [comment]
@saudet thanks for looking at this. I'll have a chance to try this probably in 48 hours.

**Comment by evanthomas** [comment]
@saudet No luck. I can see it looking in the local repository and the artefacts are there, however the artefact name that it is looking for has the string `${dependency.platform}` inserted into which is why it can't find it. However, some testing indicates it is probably a windows specific issue because it works fine on a mac I have access to. I've tried a couple of different windows shells without effect. Do you have any other suggestions?

Thanks!

**Comment by saudet** [comment]
AFAIU, it's something that's related to Ivy. Removing the the `.ivy2/cache` directory usually works for me...

**Comment by evanthomas** [comment]
@saudet Yes - that fixed it. Thanks!
