### ISSUE TITLE
0.9.1 - Java.lang.IllegalStateException: Mis matched shapes

### ISSUE THREAD

**Issue by rzykov** [deeplearning4j/nd4s#115]
Version 0.8.0:
SBT
```
val nd4jVersion = "0.8.0"

libraryDependencies += "org.nd4j" % "nd4j-native-platform" % nd4jVersion

libraryDependencies += "org.nd4j" %% "nd4s" % nd4jVersion

resolvers += "Maven" at "http://repo1.maven.org/maven2/"

```
Code
```
import org.nd4s.Implicits._
import org.nd4j.linalg.api.ndarray.INDArray
val b = Array(Array(1, 2)).toNDArray
b * b.T
```
res0: org.nd4j.linalg.api.ndarray.INDArray = [1.00, 4.00]

The same operations in 0.9.1:

> java.lang.IllegalStateException: Mis matched shapes
>   at org.nd4j.linalg.util.LinAlgExceptions.assertSameShape(LinAlgExceptions.java:45)
>   at org.nd4j.linalg.api.ndarray.BaseNDArray.muli(BaseNDArray.java:3101)
>   at org.nd4j.linalg.api.ndarray.BaseNDArray.mul(BaseNDArray.java:2865)
>   at org.nd4s.RealNDArrayEvidence$class.mul(NDArrayEvidence.scala:136)
>   at org.nd4s.DoubleNDArrayEvidence$.mul(NDArrayEvidence.scala:206)
>   at org.nd4s.OperatableNDArray$class.$times(OperatableNDArray.scala:42)
>   at org.nd4s.Implicits$RichINDArray.$times(Implicits.scala:10)
>   ... 42 elided

**Comment by rzykov** [comment]
I made an error * instead of dot
