### ISSUE TITLE
nd4s filter operation is broken

### ISSUE THREAD

**Issue by rahulpalamuttam** [deeplearning4j/nd4s#40]
nd4s now supports a filter operation used to mask values in arrays.
However this operation is prone to the following error:

Here is an example and the error it returns
 val dense = Nd4j.create(Array[Double](1, 241, 241, 1), Array(2, 2))
    val t = dense.filter(_ < 241)
    println(t)

java.lang.IllegalArgumentException: Shape must be <= buffer length
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:118)
	at org.nd4j.linalg.cpu.NDArray.<init>(NDArray.java:65)
	at org.nd4j.linalg.cpu.CpuNDArrayFactory.create(CpuNDArrayFactory.java:228)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:2894)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.create(BaseNDArray.java:3507)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.reshape(BaseNDArray.java:3547)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.reshape(BaseNDArray.java:3571)
	at org.nd4j.api.CollectionLikeNDArray$$anonfun$filteri$1.apply(CollectionLikeNDArray.scala:13)
	at org.nd4j.api.CollectionLikeNDArray$$anonfun$filteri$1.apply(CollectionLikeNDArray.scala:12)
	at org.nd4j.api.CollectionLikeNDArray$class.notCleanedUp(CollectionLikeNDArray.scala:37)
	at org.nd4j.api.Implicits$RichINDArray.notCleanedUp(Implicits.scala:10)
	at org.nd4j.api.CollectionLikeNDArray$class.filteri(CollectionLikeNDArray.scala:12)
	at org.nd4j.api.Implicits$RichINDArray.filteri(Implicits.scala:10)
	at org.nd4j.api.CollectionLikeNDArray$class.filter(CollectionLikeNDArray.scala:15)
	at org.nd4j.api.Implicits$RichINDArray.filter(Implicits.scala:10)

Note however that replacing the filter operation with an equivalent map operation that has a conditional works.

  test("filter") {
    val dense = Nd4j.create(Array[Double](1, 241, 241, 1), Array(2, 2))
    val t = dense.map(p => if (p < 241.0) p else 0.0)
    println(t)
  }

[[1.00,0.00]
 [0.00,1.00]]

**Comment by agibsonccc** [comment]
@taisukeoe is this fixed?
